@startuml lunar-lander
title lunar-lander
abstract PhysicalObject{
    #weight
    #position
    #rotation
    #speed
    #momentum
    +set_position()
    +set_speed()
    +set_momentum()
    +apply_force()
    +apply_rotation()
    +move()
}
abstract GraphicalObject{
    +{abstract}draw(SDL_Renderer*)
}

class BackgroundImage{
    +BacgroundImage()
    +~BackgrounImage()
    -generate_random_stars()
    -stars: array
}
class Game{
    +Game()
    +~Game()
    +start()
    +finish()
    +get_user_input()
    +update()
}
class Lander{
    +fuel
    +explode()
}
class Terrain{
    -hills: array
    +Terrain()
    +Terrain()
    -generate_hills()
}
class GameWindow{
    +GameWindow()
    +~GameWindow()
    -graphical_objects: list
    -window
    -renderer
    +update_graphics()
    +add_new_graphical_object()
}
class Player{
    +points
    +add_points()
    +evaluate_landing()
}
class Physics{
    -physical_objects: list
    +update_physics()
    -check_collisions()
}
class LandingZone{
    +award
    +get_points()
}
class UI{
    -ui_elements: list
    -fonts: array
}
abstract UIElement{
    -position: SDL_Point
    -size: SDL_Point
    +update_values()
    +display_ui()
    +display_message()
}
class UITextElement{
    -text:string
    -font:font_type
    +set_text()
}
class UIGraphicalElement{

}

PhysicalObject <|.. Lander
GraphicalObject <|-- PhysicalObject
GraphicalObject <|.. Terrain
Game *-- GameWindow
Player *-- Lander
Game *-- Physics
Game *-- Player
Game *-- Terrain
GraphicalObject <|.. LandingZone
Terrain *- "1.*"LandingZone
UI *-- "1.*" UIElement
GraphicalObject <|.. UIElement
Game *-- UI
GraphicalObject <|.. BackgroundImage
UIElement <|.right. UITextElement
UIElement <|.left. UIGraphicalElement
